### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by aliosmanyuksel** [ilyalyo/insta#83]
Hello,

I want to use this script my server. How can i install this? Can you help me?

Regards,

Ali Osman YUKSEL

**Comment by ilyalyo** [comment]
Hi,Since 1st of June it doesn't really works because of last instagram update.Best regards,Ilia Grabko15:20, June 11, 2016, "Ali Osman Yüksel" notifications@github.com:Hello, I want to use this script my server. How can i install this? Can you help me? Regards, Ali Osman YUKSEL —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.     -- Sent from Yandex.Mail for mobile
